### ISSUE TITLE
Domain validator now too permissive

### ISSUE THREAD

**Issue by leforestier** [kvesteri/validators#123]
Hello,

It seems any string composed of numbers separated by dots is now accepted by  the domain validator.

```
>>> validators.domain("123.123")
True

>>> validators.domain("123.123.123")
True

>>> validators.domain("123.123.123.123")
True
```

It didn't use to be the case (I know because it now causes some errors in my unit tests in the "naval" library)
I think it was good that these strings weren't accepted as domains. I don't think these are valid domains.

**Comment by alertedsnake** [comment]
Confirmed this is a regression in 0.13.0 - it works in 0.12.5.

**Comment by alertedsnake** [comment]
Although... is it a regression?  Seems like a philosophical question: "Is an IP address a valid domain name?"  Hmm...

**Comment by micahcochran** [comment]
> Although... is it a regression? Seems like a philosophical question: "Is an IP address a valid domain name?" Hmm...

.123 is not a valid [Top Level Domain](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains).  Furthermore, based on [RFC 1034](https://tools.ietf.org/html/rfc1034)'s rules it looks like a valid domain name (page 10) have to begin with a letter.

**Comment by alertedsnake** [comment]
In digging further I believe this address is not a valid domain name due to the TLD not being valid as @micahcochran said, however the matter of a valid domain name starting with a number is less clear - [RFC2181](https://tools.ietf.org/html/rfc2181#section-11) suggests othewise, and in practice, these exist in the wild.
