### ISSUE TITLE
fresh installation fails

### ISSUE THREAD

**Issue by AbdealiJK** [kvesteri/validators#19]
**Important** Could this be fixed and released in a patch version so that our users don't have an issue ? We have a FOSS Asia stall where we expect a lot of new users.

If you like, I can submit a patch ?

Hi !
I'm a maintainer of coala - https://github.com/coala-analyzer/coala and we recently started using your package in coala, because it's awesome.

We just did a release yesterday and when doing some basic testing, we found a bug in your package.

You use `setuptools` in setup.py but don't depend on it in `install_requires`. Hence, if I don't have setuptools already installed, I'm unable to install your package.

```
$ python -c "import setuptools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'setuptools'
$ pip install validators
Collecting validators
  Using cached validators-0.10.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

@ coala we normally add `setuptools>=19.2` to our install_requires and it works fine.
For example, this is what installing pyprint (one of our tools) without setuptools does:
```
$ pip install PyPrint
Collecting PyPrint
  Using cached PyPrint-0.2.3-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): termcolor~=1.1.0 in /home/ajk/.pyenv/versions/3.5.1/lib/python3.5/site-packages (from PyPrint)
Requirement already satisfied (use --upgrade to upgrade): colorama~=0.3.6 in /home/ajk/.pyenv/versions/3.5.1/lib/python3.5/site-packages (from PyPrint)
Collecting setuptools>=19.2 (from PyPrint)
  Using cached setuptools-20.3-py2.py3-none-any.whl
Installing collected packages: setuptools, PyPrint
Successfully installed PyPrint-0.2.3 setuptools-20.3
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

You can check out pyprint at https://github.com/coala-analyzer/pyprint

**Comment by sils1297** [comment]
Ping?

**Comment by AbdealiJK** [comment]
A polite reminder about this. We are moving on to our next release and this is still a problem for us.
I've made a pull request a month back - would it be possible for you to review it ?

**Comment by AbdealiJK** [comment]
Or if this is by any chance unmaintained now, do let us know so that we may fork our own package.

**Comment by sils1297** [comment]
@AbdealiJK doesn't seem too maintained, can we get rid of that dependency?

**Comment by kvesteri** [comment]
All the packages I look up to (for example Flask and SQLAlchemy) require setuptools and don't have it in install_requires, thus I don't see a reason adding it here either.
