### ISSUE TITLE
validator.url('http://127.0.0.1:8080/') fails

### ISSUE THREAD

**Issue by smtakeda** [kvesteri/validators#25]
Version: 0.10.2

Wondering if this is a new behavior? I didn't have a chance to look at the code, though..

```
from validators import url

if url('http://127.0.0.1:8080/'):
    print("success")
else:
    print("failure")
```

```
failure
```

**Comment by smtakeda** [comment]
ah, I see the internal IP is excluded

```
u"(?!(?:10|127)(?:\.\d{1,3}){3})"
```

**Comment by kvesteri** [comment]
Yes, we could maybe introduce some new parameter to this function (``local_domains`` for example) that would determine whether or not it should accept localhost or local ip addresses as valid urls.

**Comment by lconceicao** [comment]
Invalid URL: `http://127.0.0.1:4012`. Why did you consider this to be synthetically invalid? IMHO it makes no sense. If the purpose is to enforce that a URL must be remote, it should include a option to set that enforcement, but not by default.

**Comment by kvesteri** [comment]
Agreed that those should be allowed by default. I'm not a regexp expert. After hours of googling I found the best regexp for URL validation with comprehensive tests so I copied it here. Pull requests welcome.
