### ISSUE TITLE
url validator fails for 'localhost'

### ISSUE THREAD

**Issue by abingham** [kvesteri/validators#35]
I'm trying to use `validators.url()` with addresses on localhost, and it fails. For example:

```
In [8]: validators.url('http://localhost')
Out[8]: ValidationFailure(func=url, args={'public': False, 'value': 'http://localhost'})
```

Is this intentional?

**Comment by jblom** [comment]
this seems to be a problem once more since `0.21.2`. I tried to validate `http://localhost` and also `http://localhost:5555`. Both fail now.

Found this after updating my packages for my project.

**Comment by joe733** [comment]
@jblom, sorry for the inconvenience, please refer: https://github.com/python-validators/validators/issues/285#issuecomment-1676336214

**Comment by jblom** [comment]
@joe733 ah thank you very much, all clear now.
