### ISSUE TITLE
domain validator fails for äöü

### ISSUE THREAD

**Issue by georgkrause** [kvesteri/validators#47]
if a domain contains german letters like ä, ö or ü, which would be valid, the validator fails.

**Comment by commutecat** [comment]
You can use python3  str.encode('idna') 
For python 2 , make sure you convert the string to unicode. 

```
# python 3
domain_name = 'http://kräuter.com'
validators.url(domain_name.encode('idna'))

# python 2 
validators.url(domain_name.decode("utf-8").encode('idna'))

```

**Comment by georgkrause** [comment]
I know how to geht around. But thats unexpected behavior

**Comment by commutecat** [comment]
Anyway, I stop using validators.url () as there is still many fixes required : 

- it think IP address is invalid
- it think spaces in Url is bad
- it will failed on unicode.  (that's mean my work around actually doesn't works)
