### ISSUE TITLE
IPv4 formatted IP address returning True on ipv6

### ISSUE THREAD

**Issue by johndlong** [kvesteri/validators#58]
Looks like 0.12.0 is introducing support for IPv4-compatible + IPv4-mapped with #56 .

But it looks like any IPv4 address will now return True on IPv6, regardless of whether it has been prefixed to be IPv6 compatible.

```
>>> import validators
>>> validators.ipv6('::192.0.2.128')
True
>>> validators.ipv6('192.0.2.128')
True
```

**Comment by christophwischow** [comment]
Agree, same issue here. Makes this module a no go :(
