### ISSUE TITLE
Test for 3.7 is failing to start

### ISSUE THREAD

**Issue by Hultner** [kvesteri/validators#96]
The test for python 3.7 is not even succeeding to download the python interpret in travis.

I think this is because 3.7 requires a workaround with sudo: true in travis to work properly in 3.7. I can create a PR for this if you want help.

**Comment by kvesteri** [comment]
Sure why not :+1: you can create a PR

**Comment by micahcochran** [comment]
I fixed this as a part of PR #93

**Comment by Hultner** [comment]
@Micah: 3.7-dev is using an ancient pre release version of 3.7. There’s a
workaround for 3.7 proper.

**Comment by kvesteri** [comment]
Fixed.
